- id: terraform_docs
  name: Terraform docs (overwrite README.md)
  description: Overwrite content of README.md with terraform-docs.
  require_serial: true
  entry: tf_docs
  language: python
  files: (\.tf)$
  exclude: \.terraform\/.*$